In [ ]:
import pandas as pd
import numpy as np

In [ ]:
a = np.array([1, 2, 3])
b = a

In [ ]:
b[1]=90

In [ ]:
b

In [ ]:
a

In [ ]:
arr=np.zeros([3,4],dtype=int)
arr

In [ ]:
arr=np.full((2,3),7,dtype=float)
arr

In [ ]:
arr1=np.arange(2,20,4)
arr1

In [ ]:
a = np.array([[1, 2, 3], [4, 5, 6]])
a

In [ ]:
a.shape

In [ ]:
a.ndim

In [ ]:
a.size

In [ ]:
a = np.array([10, 20, 30, 40, 50,60])
print(a[a > 25])

In [ ]:
a = np.array([[1], [2], [3]])   # shape (3,1)
b = np.array([10, 20, 30])      # shape (3,)
print(a + b)

In [ ]:
a.reshape(2, 3)


In [ ]:
output=a.resize(2,3)
output


In [ ]:
a = np.array([[1, 2], [3, 4]])

a.sum()

In [ ]:
a.sum(axis=0)

In [ ]:
a.sum(axis=1)

In [15]:
row,column=input("Enter the dimention of hte array").split()
row=int(row)
column=int(column)
print(row,column,type(row),type(column))

5 5 <class 'int'> <class 'int'>


In [16]:
import numpy as np
a=np.zeros((row,column),dtype=int)
a

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [18]:
for i in list(range(row)):
    for j in list(range(column)):
        if i == 0 or j == 0 or i == (row-1) or j == (column-1):
            a[i][j] = 1

a

array([[1, 1, 1, 1, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 1, 1, 1, 1]])

In [ ]:
column1

In [21]:
a=np.ones((row,column),dtype=int)

In [22]:
a


array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [30]:
a[0,2]

np.int64(1)

In [26]:
a

array([[1, 1, 1, 1, 1],
       [1, 0, 0, 0, 1],
       [0, 0, 0, 0, 0],
       [1, 0, 0, 0, 1],
       [1, 1, 1, 1, 1]])

In [2]:
import numpy as np
a=np.zeros((8,8))

In [3]:
a

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [4]:
a[::2,::2]=1
a

array([[1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [5]:
a[1::2,1::2]=1
a

array([[1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.]])

In [6]:
import numpy as np
a=np.zeros((8,8))
a[::2,::2]=1
a[1::2,1::2]=1
a

array([[1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.]])

In [12]:
a = np.array([4, 8, 15, 16, 23, 42])
result = (a-a.min())/(a.max() - a.min())
result

array([0.        , 0.10526316, 0.28947368, 0.31578947, 0.5       ,
       1.        ])

In [2]:
import numpy as np
a = np.array([-3, 7, 2, -1, 9, 4, -5, 6, 0])

In [3]:
a[a < 0]=0
a[a > 5]=5
a

array([0, 5, 2, 0, 5, 4, 0, 5, 0])

In [12]:
a = np.array([1, -3, 4, -2, 5, 6, -7, 8, -1])
result = (a < 0).sum()
result

np.int64(4)

In [13]:
a = np.arange(1, 21)
a[a %2 == 0]

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [ ]:
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
result = 

In [17]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [19]:
a = np.array([10, 20, 30, 40, 50])
a[::-1]

array([50, 40, 30, 20, 10])

In [20]:
a = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

In [22]:
a[::-1,::]


array([[7, 8, 9],
       [4, 5, 6],
       [1, 2, 3]])

In [23]:
a = np.arange(1, 26).reshape(5, 5)

In [24]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [25]:
a[1:-1,1:-1]

array([[ 7,  8,  9],
       [12, 13, 14],
       [17, 18, 19]])

In [29]:
a = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]], dtype=float)

a.mean(axis=0)

array([4., 5., 6.])

In [30]:
a - a.mean(axis=0)

array([[-3., -3., -3.],
       [ 0.,  0.,  0.],
       [ 3.,  3.,  3.]])

In [40]:
a = np.array([7, 2, 9, 4, 1, 8, 3, 6, 5])
np.sort(a)[-3:][::-1]

array([9, 8, 7])

In [ ]:
a


array([1, 2, 3])

In [41]:
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

In [42]:
result = np.where(a%2!=0,-1,a)
result

array([-1,  2, -1,  4, -1,  6, -1,  8, -1, 10])

In [43]:
import pandas as pd
import numpy as np

df = pd.DataFrame({
    'name':   ['Alice', 'Bob', 'Charlie', 'Diana', 'Ethan'],
    'age':    [25, 30, 35, 28, 40],
    'city':   ['NYC', 'LA', 'NYC', 'Chicago', 'LA'],
    'salary': [70000, 85000, 120000, 90000, 110000]
})

In [44]:
df.age

0    25
1    30
2    35
3    28
4    40
Name: age, dtype: int64

In [45]:
df['age']

0    25
1    30
2    35
3    28
4    40
Name: age, dtype: int64

In [48]:
df.sort_values(by='salary', ascending=False).reset_index(drop=True)

,name,age,city,salary
0,Charlie,35,NYC,120000
1,Ethan,40,LA,110000
2,Diana,28,Chicago,90000
3,Bob,30,LA,85000
4,Alice,25,NYC,70000
